# .github/workflows/ci-cd.yml

name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install rsync
        run: |
          sudo apt update
          sudo apt install rsync -y

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          rsync . root@$SERVER_IP:/var/www/html
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{secrets.SERVER_IP}}

      - name: Restart Server
        run: |
          ssh root@$SERVER_IP <<EOF
          chmod -R 777 /var/www/html
          systemctl restart apache2
          EOF
        env:
          SERVER_IP: ${{secrets.SERVER_IP}}
