# .github/workflows/ci-cd.yml

name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]
    
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install rsync
        run: |
          sudo apt update
          sudo apt install rsync -y

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          rsync -avz --exclude '.env' --exclude 'vendor/' ./ $SSH_USER@$SERVER_IP:/var/www/html/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }} 
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: SSH into Server and Restart Apache
        run: |
          ssh $SSH_USER@$SERVER_IP 'sudo chmod -R 777 /var/www/html && sudo systemctl restart apache2'
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Deployment Status
        run: |
          echo 'Deployment successful to Digital Ocean'
